# Generated by Django 5.2 on 2025-04-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_transaction_converted_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='converted_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='original_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='target_currency',
        ),
    ]
