# Generated by Django 5.2 on 2025-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_delete_currencyrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('SUM', 'Uzbek Sum')], max_length=3),
        ),
    ]
