# Generated by Django 5.2 on 2025-04-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_alter_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
