# Generated by Django 5.2 on 2025-04-29 21:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_alter_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
